### ISSUE TITLE
next ocurrency of  2021-05-31 is 2021-07-31 when only monthly is used  is rule

### ISSUE THREAD

**Issue by bruteforcecat** [peek-travel/cocktail#180]
```

(~U[2021-05-31 00:00:00Z]
|> Cocktail.schedule()
|> Cocktail.Schedule.add_recurrence_rule(:monthly)
|> Cocktail.Schedule.occurrences(~U[2021-05-31 00:00:01Z])
|> Enum.take(1)) # return ~U[2021-07-31 00:00:00Z]
```
So it looks like the day in start_time is used implicitly as days_of_month filter. I can't see related info in iCalendar rfc.

I personally will expect it return the last day of the month(2021-6-30) for the above example.  I can make a PR fixing this if we think this is a bug.

**Comment by taddeimania** [comment]
Was there any offline discussion regarding this issue? I'm encountering this as an issue for generating occurrences that happen monthly near the end of the month.  Day 31 skips various months, and Feb 29 skips Feb on non-leap years.  Can we have those cases default to the last day of the month if a day of month is > the amount of days in the month?

**Comment by doughsay** [comment]
I have another project, [Excal](https://github.com/peek-travel/excal) which implements a NIF that uses the libical reference implementation, so it should follow the iCalendar spec as closely as anything does, as far as I know.  If you try something similar out in Excal, you get this:

```elixir
iex(5)> {:ok, stream} = Excal.Recurrence.Stream.new("FREQ=MONTHLY", ~D[2021-05-31])
{:ok, #Function<51.58486609/2 in Stream.resource/3>}
iex(6)> Enum.take(stream, 5)
[~D[2021-05-31], ~D[2021-07-31], ~D[2021-08-31], ~D[2021-10-31], ~D[2021-12-31]]
```

So I'm pretty sure the iCalendar spec says to skip months where that month-day doesn't exist, which is why I originally made Cocktail behave this way as well.

If you actually wanted "monthly on the last day of the month", then you could accomplish it this way:

```elixir
iex(7)> {:ok, stream} = Excal.Recurrence.Stream.new("FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1", ~D[2021-05-31])
{:ok, #Function<51.58486609/2 in Stream.resource/3>}
iex(8)> Enum.take(stream, 5)
[~D[2021-05-31], ~D[2021-06-30], ~D[2021-07-30], ~D[2021-08-31], ~D[2021-09-30]]
```

...but unfortunately, Cocktail doesn't support the "by set position" feature.  So I'm closing this issue, but please feel free to open a feature request ticket to implement "set position", or please take a look at Excal to see if it fits your use-case better.
