### ISSUE TITLE
How to go about storing a cocktail schedule in the database?

### ISSUE THREAD

**Issue by MarbilleJuntado** [peek-travel/cocktail#185]
Say, I wanted to add a field in my table that represents a cocktail schedule's recurrence rule, what data type should I use? And in the schema, how should it look like?

**Comment by doughsay** [comment]
Me personally I use a `text` column type in postgres and I convert `Cocktail.Schedule` structs to iCalendar format using `Cocktail.Schedule.to_i_calendar/1`: https://hexdocs.pm/cocktail/Cocktail.Schedule.html#to_i_calendar/1.  Then when loading from the database you can convert it back into a schedule struct using `Cocktail.Schedule.from_i_calendar/1`: https://hexdocs.pm/cocktail/Cocktail.Schedule.html#from_i_calendar/1

If you wanted to get really fancy you could write your own custom Ecto type that does the serialization and deserialization for you so that from your application it appears as if you are storing and reading the structs directly: https://hexdocs.pm/ecto/Ecto.Type.html
