### ISSUE TITLE
Missing RRULE options

### ISSUE THREAD

**Issue by austinh** [peek-travel/cocktail#48]
Hi there, I'm interested in using this library for a project I am working on and I am looking to support the full RRULE spec. I see it is on the roadmap.

I have been looking into the code, and wondered what parts of the RRULE option are not currently supported? I would love to contribute and help flesh out any missing pieces.

**Comment by austinh** [comment]
@doughsay thanks, I'll look into what it would take to potentially add monthly and yearly because those are a must have for me. I will also take a look at your excal libical integration and see how it works. I have no experience with NIFs or C though. Hopefully its performant and safe. :)

**Comment by doughsay** [comment]
@austinh it's much more performant than cocktail, usually about 10x faster.  As for safe, yeah that remains to be seen.  A segfault in the C code will crash the BEAM.  I had several problems during development, but after fixing those I haven't seen any since.  Tests and benchmarks seem stable.  That being said, I am NOT yet using it in production.  But I might be soon...
