### ISSUE TITLE
ETA for :monthly and : days_of_month support

### ISSUE THREAD

**Issue by tommyblue** [peek-travel/cocktail#73]
Hi, I'm migrating a rails app to phoenix and I used ice_cube, so this project seems very handy for my migration. Unfortunately, I'd need montly support.

Do you have any ETA for its support?
Thanks!

**Comment by doughsay** [comment]
Sorry, I currently have no plans to add these features to cocktail, since it currently works for my purposes as is.  I would be glad however to accept any pull-requests to help add new features.

If you'd like to give this more experimental library a try, it might help you: https://github.com/peek-travel/excal  It binds directly to the c reference implementation, libical, and supports all recurrence rule features that the standard does.  But at the moment there's no real documentation on how to get it compiling and working.  I'm going to improve that this weekend though, so stay tuned!

As a bonus, excal is MUCH faster than cocktail;  CPU intensive operations in Elixir, especially date-math, are just a bit too slow for my tastes...

**Comment by tommyblue** [comment]
I'll take a look to the code, let's see if I can add this feature

**Comment by doughsay** [comment]
Added by #138
